---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- name: Check for boto packages
  shell: rpm -qa |grep python2-boto |echo $?
  register: HaveBoto
  ignore_errors: True

- name: Set HaveBoto fact
  set_fact:
    HaveBoto: "{{ HaveBoto.stdout_lines[0] }}"

- name: Install Dependencies for getting boto packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
  when: 
    - ansible_os_family == "RedHat"
    - HaveBoto == 0

- name: Get EPEL Repo rpm
  shell: wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  args:
    chdir: /root
    creates: /root/epel-release-latest-7.noarch.rpm
    warn: false
  when: 
    - ansible_os_family == "RedHat"
    - HaveBoto == 0

- name: Add EPEL Repo rpm
  shell: rpm -ivh epel-release-latest-7.noarch.rpm
  args:
    chdir: /root
    warn: False
    creates: /etc/yum.repos.d/epel.repo
  when: 
    - ansible_os_family == "RedHat"
    - HaveBoto == 0

- name: Install boto packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python2-boto
    - python2-boto3
  when: 
    - ansible_os_family == "RedHat"
    - HaveBoto == 0

- name: Make local files directory
  file:
    path: "{{ RC_PLAY_TOP }}/files"
    state: directory

- name: Copy the SSH id_rsa.pub to our files directory
  copy: 
    src: /root/.ssh/id_rsa.pub
    dest: "{{ RC_PLAY_TOP }}/files/id_rsa.pub"

- name: Copy the SSH id_rsa to our files directory
  copy: 
    src: /root/.ssh/id_rsa
    dest: "{{ RC_PLAY_TOP }}/files/id_rsa"

- name: Remove VPN Server tun0 IP from SSH knownhosts
  lineinfile:
    dest: /root/.ssh/known_hosts
    state: absent
    regexp: "^{{ SERVER_IP|regex_escape() }}.*"

