---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

# Load AWS variables
- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

# Load Inventory file for VPN
- include_vars: "{{ RC_PLAY_TOP }}/inventory_ec2.yml"

- include: make-ec2-servers.yml

